[project]
name = "bleakfaith-tool"
version = "0.1.0"
description = "Tools to work with Bleak Faith: Forsaken"
readme = "README.md"
authors = [
    { name = "Adam Hellberg", email = "sharparam@sharparam.com" }
]
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
    "pytest>=9.1.1",
    "structlog>=26.1.0",
]

[project.scripts]
bleakfaith-tool = "bleakfaith_tool:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.3",
    "ty>=0.0.73",
]
